on:
  workflow_dispatch:
  
jobs:
  call-workflow-passing-data:
    uses: ashrafalih/RepoB/.github/workflows/called.yml@main
    with:
      config-path: hello
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
