name: Dynamic Value Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      # Define the output variable
      deploy_env: ${{ steps.get_env.outputs.get_env }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Dynamic Value
        id: get_env
        run: |
          # Generate a dynamic value (you can replace this with your logic)
          get_env="generated-value-$(date +%s)"
          echo "Dynamic Value: $get_env"

          # Set the output variable
          echo "::set-output name=get_env::$get_env"

  test:
    runs-on: ubuntu-latest
    needs: build

    outputs:
      deploy_env: ${{ needs.build.outputs.deploy_env }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          # Access the dynamic value passed from the build job
          echo "Testing with dynamic value: ${{ needs.build.outputs.deploy_env }}"
