name: Dynamic Value Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      # Define the output variable
      id: dynamic_value
      value: ${{ steps.set-dynamic-value.outputs.dynamic_value }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Dynamic Value
        id: set-dynamic-value
        run: |
          # Generate a dynamic value (you can replace this with your logic)
          dynamic_value="generated-value-$(date +%s)"
          echo "Dynamic Value: $dynamic_value"

          # Set the output variable
          echo "::set-output name=dynamic_value::$dynamic_value"

      - name: Build
        run: |
          # Use the dynamic value in the build step
          echo "Building with dynamic value: ${{ needs.build.outputs.dynamic_value }}"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          # Access the dynamic value passed from the build job
          echo "Testing with dynamic value: ${{ needs.build.outputs.dynamic_value }}"
